
services:
  app:
    build: .
    environment:
      - APP_MESSAGE=Running via Compose!
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - database

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  database:
    image: mysql:8  
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: dockerlearning
      MYSQL_USER: root
      MYSQL_PASSWORD: root
   